### ISSUE TITLE
[Feature Request] 希望能够多一些自定义参数

### ISSUE THREAD

**Issue by HandwerSTD** [HarmonyOS-Next/mini-calendar#1]
组件质量很高很实用，显示效果也很棒，美中不足的就是组件的自定义参数较少，希望能开放更多的一些参数。我这里列举一些我个人可能比较常用的：

- 支持自定义单个日期的样式，如日期数字背后的圆形可改为方形或其他形状，日期数字可以调整大小，不仅仅是颜色；当前月份两侧的月份（浅灰色显示的数字）希望也能够自定义，方便用户快捷观察跨月份选择的日期
- 支持自定义展示的起始日期，以及快速返回今日
- 支持自定义行数量，比如由默认的6行缩短至4行
- 支持整体面板的颜色设定，方便适配深色模式
- 提供一个 `controller` 用于自动化跳转日历到指定月份，适用于有外部控制展示日期参数的场景

**Comment by zhousg** [comment]
## Release 2.1.2
- add selected item radius
- add calendar row auto
- add controller changeMonth
- add dark mode

增加圆角，用户深度自定后期将支持 BuildParam 
支持行数自动，可以根据当月天数自动显示，不能设置4行可能一月天数显示不全
组件本身支持深色模式无需应用控制
增加controller支持，上一个月 下一个月 当前月  切换到目标月

发布通过便可使用
