### ISSUE TITLE
ui无法监听刷新

### ISSUE THREAD

**Issue by WhiteNight0212** [HarmonyOS-Next/mini-calendar#2]
例如点击日期后无法使选中的日期变化样式，
关键点在 无法监听到 item数组元素的属性变化，只能监听到数组的增删
` @State
  items: HmCalendarItem[] = []`
想了解下你的api版本，或者解决方案
我的是api11，试过@ Track，但是不生效
@ObjectLink可以但是得抽离成子组件，太冗余

**Comment by zhousg** [comment]
重新替换下数组，组件内没有使用。另外的一个项目有api11 的日历源码 和使用代码
features/mine/src/main/ets/views/ClockedComp.ets

**Comment by WhiteNight0212** [comment]
ok
