### ISSUE TITLE
期望由开发者自己定义是否显示日历的头部 - 选择月份的那部分UI显示

### ISSUE THREAD

**Issue by skyrejer** [HarmonyOS-Next/mini-calendar#4]
![Clip_2024-10-23_14-10-32](https://github.com/user-attachments/assets/92277dd5-cf53-467c-8607-06d56413573f)
我做的这个日历界面，页面自带一个选择日期的东西，再把你这个日历引入后没办法消除日历的头部，如果可以消除日历的头部，其实控制日历的月份切换我觉得可以用日历自带的controller来实现的

**Comment by zhousg** [comment]
这几天，我更新下，注意更新版本哈

使用的时候，加上一个属性即可    showToolBar="false"

**Comment by zhousg** [comment]
审核太快了，已更新哈

**Comment by skyrejer** [comment]
谢谢



在 2024-10-23 17:46:15，"ShuGang Zhou" ***@***.***> 写道：

这几天，我更新下，注意更新版本哈

使用的时候，加上一个属性即可 showToggleBar="false"
